services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile

    image: thesis-discord-bot:latest

    env_file:
      - .env

    environment:
      SERVICES_CONFIG_PATH: /app/config/services.json
      RUNTIME_CONFIG_PATH: /app/config/runtime.json

    volumes:
      - ./instance/config:/app/config
      - ./data:/app/data
      - ./logs:/app/logs

    restart: unless-stopped